# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1blLHyKGSCv1mdP7jlnVFsMC1bEVs35iT
"""

import streamlit as st
import pandas as pd
from streamlit_gsheets import GSheetsConnection
from datetime import datetime
import numpy as np
import re
import torch
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from transformers import AutoTokenizer, AutoModel
import faiss

# --- PAGE SETUP ---
# 1. Paper Title & Subtitle
st.markdown(
    "<h1 style='font-size: 32px; text-transform: uppercase;'>⚖️ beyond case-level retrieval: proposing an argument-level schema for verbatim argument retrieval from indian judicial decisions</h1>", 
    unsafe_allow_html=True
)

st.markdown(
    "<h3 style='font-size: 20px; text-transform: uppercase; color: gray;'>A Pilot Study Demonstrated on Section 115 of the Code of Civil Procedure, 1908</h3>", 
    unsafe_allow_html=True
)

# 2. Author Credit & 3. What to Expect
st.info("""
**About this Prototype:** This site is a proof of concept supporting the research idea by **[Soubhagyashree Das](https://www.linkedin.com/in/soubhagyashree/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BXh%2Fws045RXynY8fZcxx2qA%3D%3D)**, a law student.

**What to Expect:** Instead of just returning full case files, this tool is designed to drill down into the specifics. By entering case facts or a legal issue, the system retrieves highly relevant **verbatim arguments** made in court, mapped directly to the court's reasoning and the underlying rule of law. It leverages a hybrid AI search approach to surface precise legal arguments concerning Section 115 of the CPC.
""")
st.divider()

# --- 1. CACHE DATA LOADING ---
@st.cache_data
def load_data():
    # Make sure your excel file is in the same folder as this app.py file on GitHub
    EXCEL_PATH = 'Sectioncpc115.xlsx'
    df = pd.read_excel(EXCEL_PATH)
    df.columns = df.columns.str.strip().str.replace('"', '').str.upper()
    df = df.dropna(subset=['ARGUMENT TEXT'], how='all').reset_index(drop=True)

    def normalise_outcome(val):
        v = str(val).strip().upper()
        if v in ['NAN', '-', '', 'NONE']: return 'Unknown'
        if 'PARTIAL' in v: return 'Partially Accepted'
        if 'ACCEPT' in v: return 'Accepted'
        if 'REJECT' in v: return 'Rejected'
        return str(val).strip()

    df['OUTCOME_CLEAN'] = df['ACCEPTED / REJECTED'].apply(normalise_outcome)

    def build_searchable_text(row):
        rl  = str(row.get('RULE OF LAW', '') or '')
        kw  = str(row.get('KEYWORD', '') or '')
        iss = str(row.get('ISSUE', '') or '')
        arg = str(row.get('ARGUMENT TEXT', '') or '')
        cr  = str(row.get('COURT REASONING', '') or '')
        fct = str(row.get('FACTS', '') or '')
        parts = [arg, cr, fct, iss, f"{rl} {rl} {rl}", f"{kw} {kw} {kw}"]
        combined = ' '.join(p for p in parts if p and p.lower() not in ['nan','none',''])
        return re.sub(r'\s+', ' ', combined).strip()

    texts = [build_searchable_text(row) for _, row in df.iterrows()]
    valid_mask = [len(t) > 20 for t in texts]
    df = df[valid_mask].reset_index(drop=True)
    texts = [t for t, v in zip(texts, valid_mask) if v]

    principle_texts = []
    for _, row in df.iterrows():
        rl  = str(row.get('RULE OF LAW', '') or '')
        kw  = str(row.get('KEYWORD', '') or '')
        iss = str(row.get('ISSUE', '') or '')
        t   = re.sub(r'\s+', ' ', f"{rl} {kw} {iss}").strip()
        principle_texts.append(t if len(t) > 5 else 'general revision jurisdiction Section 115 CPC')

    return df, texts, principle_texts

# --- 2. CACHE MODELS AND INDEXES ---
@st.cache_resource
def load_models_and_build_indexes(texts, principle_texts):
    # Stage 1: all-MiniLM
    model_stage1 = SentenceTransformer('all-MiniLM-L6-v2')
    embeddings = model_stage1.encode(texts, batch_size=32, convert_to_numpy=True)
    faiss.normalize_L2(embeddings)
    dimension = embeddings.shape[1]
    index = faiss.IndexFlatIP(dimension)
    index.add(embeddings)

    # TF-IDF
    tfidf_full = TfidfVectorizer(max_features=15000, ngram_range=(1, 3), min_df=1, sublinear_tf=True)
    matrix_full = tfidf_full.fit_transform(texts)

    tfidf_principle = TfidfVectorizer(max_features=10000, ngram_range=(1, 3), min_df=1, sublinear_tf=True)
    matrix_principle = tfidf_principle.fit_transform(principle_texts)

    # Stage 2: InLegalBERT
    INLEGALBERT_MODEL = "law-ai/InLegalBERT"
    inlegal_tokenizer = AutoTokenizer.from_pretrained(INLEGALBERT_MODEL)
    inlegal_model = AutoModel.from_pretrained(INLEGALBERT_MODEL)
    inlegal_model.eval()

    return model_stage1, index, tfidf_full, matrix_full, tfidf_principle, matrix_principle, inlegal_tokenizer, inlegal_model

# Load everything (this only takes time on the very first run)
with st.spinner("Loading AI Models and Legal Database... (This takes a minute on startup)"):
    df, texts, principle_texts = load_data()
    model_stage1, index, tfidf_full, matrix_full, tfidf_principle, matrix_principle, inlegal_tokenizer, inlegal_model = load_models_and_build_indexes(texts, principle_texts)

# --- 3. HELPER FUNCTIONS ---
LEGAL_SYNONYMS = {
    # Procedural terms
    'written statement':     'written statement pleading amendment Order 6 Rule 17',
    'plaint':                'plaint suit proceeding filing',
    'injunction':            'injunction interim order stay interlocutory temporary',
    'stay':                  'stay injunction interim order suspension',
    'appeal':                'appeal appellate decree final order first appeal',
    'revision':              'revision revisional jurisdiction Section 115 CPC supervisory High Court',
    'review':                'review revision recall order',
    'execution':             'execution decree executing court compliance',

    # Jurisdiction terms
    'jurisdiction':          'jurisdiction vested material irregularity clause (a) clause (b) clause (c) Section 115',
    'no jurisdiction':       'jurisdiction not vested clause (a) Section 115 CPC excess of jurisdiction',
    'wrong jurisdiction':    'jurisdiction not vested clause (a) Section 115 material irregularity',
    'exceeded jurisdiction': 'jurisdiction not vested clause (a) material irregularity Section 115',
    'interlocutory':         'interlocutory interim order not finally decided suit proceeding proviso amendment 1999',
    'interim order':         'interim order interlocutory not finally decided maintainability proviso',
    'final order':           'final order decree case decided suit disposed',
    'preliminary issue':     'preliminary issue case decided interlocutory order Section 115 clause (c)',

    # Parties
    'tenant':                'tenant landlord rent eviction lease Rent Act Rent Control',
    'landlord':              'landlord tenant rent eviction Rent Control Act',
    'plaintiff':             'plaintiff petitioner appellant party suit',
    'defendant':             'defendant respondent written statement',
    'petitioner':            'petitioner revision applicant High Court Section 115',
    'respondent':            'respondent opposite party revision',

    # High Court powers
    'high court':            'High Court supervisory jurisdiction Art 227 Article 227 revision Section 115',
    'article 226':           'Article 226 writ certiorari judicial order civil court',
    'article 227':           'Article 227 supervisory jurisdiction subordinate court interlocutory',
    'writ':                  'writ certiorari Article 226 Article 227 supervisory jurisdiction',
    'certiorari':            'certiorari writ Article 226 judicial order civil court jurisdictional error',
    'supervisory':           'supervisory jurisdiction Article 227 High Court subordinate court',
    'mandamus':              'mandamus writ jurisdiction High Court Article 226',

    # Evidence and findings
    'evidence':              'evidence re-appreciation finding of fact perverse misreading',
    'finding of fact':       'finding of fact re-appreciation evidence perverse revisional jurisdiction',
    'perverse':              'perverse finding no evidence misreading re-appreciation',
    'concurrent finding':    'concurrent finding both courts revisional jurisdiction interference',
    're-appreciate':         're-appreciation evidence finding of fact revisional jurisdiction exceeded',
    'second appeal':         'second appeal appellate jurisdiction re-appreciation findings',

    # Orders and errors
    'material irregularity': 'material irregularity clause (c) Section 115 CPC exercise jurisdiction',
    'error of law':          'error of law jurisdiction Section 115 material irregularity',
    'refused to decide':     'failed to exercise jurisdiction clause (b) Section 115',
    'declined to hear':      'failed to exercise jurisdiction clause (b) Section 115',
    'ignored':               'failed to exercise jurisdiction material irregularity clause (b) clause (c)',
    'dismissed':             'dismissed rejected order interlocutory revision',

    # Special contexts
    'arbitration':           'arbitration Section 37 Arbitration Act Article 227 judicial interference',
    'lok adalat':            'Lok Adalat award decree Legal Services Authorities Act execution',
    'rent control':          'Rent Control Act legality propriety revisional jurisdiction re-appreciation',
    'amendment':             'amendment 1999 proviso Section 115 interlocutory finally dispose suit',
    'subletting':            'subletting oral written consent Rent Restriction Act revisional jurisdiction',
    'registered document':   'registered document sham transaction inference revisional jurisdiction',

    # Clause-specific triggers
    'clause a':              'jurisdiction not vested clause (a) Section 115 CPC excess jurisdiction',
    'clause b':              'failed to exercise jurisdiction clause (b) Section 115 CPC',
    'clause c':              'material irregularity clause (c) Section 115 CPC exercise jurisdiction',
    'not vested':            'jurisdiction not vested clause (a) Section 115 CPC',
    'failed to exercise':    'failed to exercise jurisdiction clause (b) Section 115',
}

def expand_query(query):
    expanded = query
    query_lower = query.lower()
    matched = []
    for term, expansion in LEGAL_SYNONYMS.items():
        if term.lower() in query_lower:
            expanded += ' ' + expansion
            matched.append(term)
    return expanded, matched

def get_inlegalbert_embedding(text, max_length=512):
    inputs = inlegal_tokenizer(text, return_tensors='pt', truncation=True, max_length=max_length, padding=True)
    with torch.no_grad():
        outputs = inlegal_model(**inputs)
    attention_mask = inputs['attention_mask']
    token_embeddings = outputs.last_hidden_state
    mask_expanded = attention_mask.unsqueeze(-1).float()
    sum_embeddings = (token_embeddings * mask_expanded).sum(dim=1)
    sum_mask = mask_expanded.sum(dim=1).clamp(min=1e-9)
    return (sum_embeddings / sum_mask).squeeze().numpy()

def inlegalbert_similarity(query_text, candidate_text):
    q_emb = get_inlegalbert_embedding(query_text)
    c_emb = get_inlegalbert_embedding(candidate_text)
    dot = np.dot(q_emb, c_emb)
    norm = np.linalg.norm(q_emb) * np.linalg.norm(c_emb)
    return float(dot / norm) if norm > 0 else 0.0

def search_system(query, top_k=5, candidate_pool=20):
    expanded_query, matched_terms = expand_query(query)

    # Stage 1
    query_embedding = model_stage1.encode([expanded_query], convert_to_numpy=True)
    faiss.normalize_L2(query_embedding)
    k = min(candidate_pool * 4, len(texts))
    sem_scores_raw, sem_indices = index.search(query_embedding, k)
    sem_scores = {int(idx): float(score) for idx, score in zip(sem_indices[0], sem_scores_raw[0]) if idx >= 0}

    qvec_full = tfidf_full.transform([expanded_query])
    scores_full_raw = cosine_similarity(qvec_full, matrix_full).flatten()

    qvec_principle = tfidf_principle.transform([expanded_query])
    scores_principle_raw = cosine_similarity(qvec_principle, matrix_principle).flatten()

    def norm_dict(d): return {k: v/max(d.values()) for k,v in d.items()} if d and max(d.values()) > 0 else d
    def norm_arr(arr): return arr / arr.max() if arr.max() > 0 else arr

    sem_norm = norm_dict(sem_scores)
    full_norm = norm_arr(scores_full_raw)
    principle_norm = norm_arr(scores_principle_raw)

    final_scores = {}
    for idx in range(len(texts)):
        final_scores[idx] = (sem_norm.get(idx, 0)*0.40) + (float(full_norm[idx])*0.30) + (float(principle_norm[idx])*0.30)

    ranked = sorted(final_scores.items(), key=lambda x: x[1], reverse=True)[:candidate_pool]

    candidates = []
    for idx, score in ranked:
        if score < 0.01: continue
        row = df.iloc[idx]
        candidates.append({
            'hybrid_score': round(score, 4), 'matched_synonyms': matched_terms,
            'case_name': str(row.get('CASE NAME', 'N/A')), 'citation': str(row.get('CITATION', 'N/A')),
            'forum': str(row.get('FORUM', 'N/A')), 'party': str(row.get('PARTY', 'N/A')),
            'issue': str(row.get('ISSUE', 'N/A')), 'argument': str(row.get('ARGUMENT TEXT', 'N/A')),
            'arg_para': str(row.get('ARG PARA NO.', 'N/A')), 'court_reasoning': str(row.get('COURT REASONING', 'N/A')),
            'court_para': str(row.get('COURT PARA NO.', 'N/A')), 'outcome': str(row.get('OUTCOME_CLEAN', 'N/A')),
            'rule_of_law': str(row.get('RULE OF LAW', 'N/A')), 'keyword': str(row.get('KEYWORD', 'N/A')),
            'link': str(row.get('LINK', 'N/A'))
        })

    # Stage 2: Re-rank
    reranked = []
    for c in candidates:
        candidate_text = f"{c['argument']} {c['rule_of_law']}"
        rl_score_norm = (inlegalbert_similarity(query, candidate_text) + 1) / 2
        final = (0.70 * c['hybrid_score']) + (0.30 * rl_score_norm)
        reranked.append({**c, 'score': round(final, 4)})

    reranked.sort(key=lambda x: x['score'], reverse=True)
    return [r for r in reranked[:top_k] if r['score'] >= 0.01]

# --- UI FRONTEND ---
st.markdown("### Enter Case Facts & Issue")
user_query = st.text_area("Type your query in plain language here...", height=150, placeholder="Example: The trial court allowed an amendment to the plaint after the trial had commenced...")

# 1. Use session state to remember results so the feedback box works
if 'search_results' not in st.session_state:
    st.session_state.search_results = None
if 'last_query' not in st.session_state:
    st.session_state.last_query = ""

if st.button("Search Arguments", type="primary"):
    if user_query.strip():
        with st.spinner("Searching and Re-ranking..."):
            results = search_system(user_query, top_k=5)
            
            # Save results and query to session state
            st.session_state.search_results = results
            st.session_state.last_query = user_query
            
            if results:
                # --- AUTO-SAVE SEARCH HISTORY TO GOOGLE SHEETS ---
              try:
                    conn = st.connection("gsheets", type=GSheetsConnection)
                    top_cases = " | ".join([r['case_name'] for r in results])
                    
                    new_row = pd.DataFrame([{
                        "Timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                        "Query": user_query,
                        "Top Cases": top_cases,
                        "User Review": "Auto-saved search log" 
                    }])
                    
                    # FIX 1: Read ONLY the first 4 columns (indexes 0, 1, 2, 3)
                    existing_data = conn.read(worksheet="Legal_App_Logs", usecols=[0, 1, 2, 3]) 
                    
                    # FIX 2: Drop the hundreds of blank rows Google Sheets leaves at the bottom
                    existing_data = existing_data.dropna(how="all")
                    
                    if not existing_data.empty:
                        updated_data = pd.concat([existing_data, new_row], ignore_index=True)
                    else:
                        updated_data = new_row
                    
                    updated_data = updated_data.fillna("")
                    updated_data = updated_data.astype(str)
                        
                    conn.update(worksheet="Legal_App_Logs", data=updated_data)
                except Exception as e:
                    st.warning(f"Background save to database failed: {e}")
            else:
                st.warning("No relevant arguments found. Try rephrasing.")
    else:
        st.warning("Please enter a query first.")

# 2. DISPLAY RESULTS (if they exist in session state)
if st.session_state.search_results:
    results = st.session_state.search_results
    st.success(f"Found {len(results)} highly relevant arguments.")
    
    if results[0]['matched_synonyms']:
        st.info(f"**Synonyms matched:** {', '.join(results[0]['matched_synonyms'])}")
    
    for i, r in enumerate(results):
        with st.expander(f"#{i+1} | {r['case_name']} ({r['outcome']}) - Score: {r['score']}", expanded=(i==0)):
            st.markdown(f"**Citation:** {r['citation']} | **Forum:** {r['forum']} | **Party:** {r['party']}")
            if r['issue'] != 'nan': st.markdown(f"**Issue:** {r['issue']}")
            st.markdown(f"**Argument (Para {r['arg_para']}):**\n> {r['argument']}")
            st.markdown(f"**Court Reasoning (Para {r['court_para']}):**\n> {r['court_reasoning']}")
            if r['rule_of_law'] != 'nan': st.markdown(f"**Principle:** {r['rule_of_law']}")
            if r['link'] != 'nan': st.markdown(f"[Read Full Source]({r['link']})")

    st.divider()
    
    # 3. OPTIONAL FEEDBACK BOX
    st.markdown("#### 📝 Optional: Help improve this research!")
    with st.form("feedback_form", clear_on_submit=True):
        feedback_text = st.text_area("Did these results help? Were any arguments irrelevant?")
        submit_feedback = st.form_submit_button("Submit Feedback")
        
        if submit_feedback and feedback_text.strip():
           try:
                conn = st.connection("gsheets", type=GSheetsConnection)
                top_cases = " | ".join([r['case_name'] for r in st.session_state.search_results])
                
                feedback_row = pd.DataFrame([{
                    "Timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                    "Query": st.session_state.last_query,
                    "Top Cases": top_cases,
                    "User Review": feedback_text 
                }])
                
                # FIX 1: Read ONLY the first 4 columns
                existing_data = conn.read(worksheet="Legal_App_Logs", usecols=[0, 1, 2, 3]) 
                
                # FIX 2: Drop all the blank rows
                existing_data = existing_data.dropna(how="all")
                
                if not existing_data.empty:
                    updated_data = pd.concat([existing_data, feedback_row], ignore_index=True)
                else:
                    updated_data = feedback_row
                
                updated_data = updated_data.fillna("")
                updated_data = updated_data.astype(str)
                    
                conn.update(worksheet="Legal_App_Logs", data=updated_data)
                st.success("Thank you! Your feedback has been recorded.")
            except Exception as e:
                st.error(f"Failed to save feedback: {e}")
